export enum PRIORITY {
  DEFAULT = 'default',
  NORMAL = 'normal',
  HIGH = 'high',
}

export enum SEX {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum CIVIL_STATUS {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  SEPARATED = 'SEPARATED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}

export enum SMOKER_STATUS {
  ACTIVE = 'ACTIVE',
  STOPPED = 'STOPPED',
  FORMER = 'FORMER',
}

export enum ALCOHOLIC_STATUS {
  ACTIVE = 'ACTIVE',
  STOPPED = 'STOPPED',
  FORMER = 'FORMER',
}

export enum EATING_BEHAVIOR {
  HYPERPHAGIC = 'HYPERPHAGIC',
  NIBBLER = 'NIBBLER',
  NIGHT_HUNGER = 'NIGHT_HUNGER',
}

export enum ENVIRONMENT {
  CALM = 'CALM',
  ACCOMPANIED = 'ACCOMPANIED',
  AGITATED = 'AGITATED',
  ALONE = 'ALONE',
}

export enum FAMILIAR_BACKGROUND {
  SAH = 'SAH',
  DM = 'DM',
  OBESITY = 'OBESITY',
  CARDIOPATHIES = 'CARDIOPATHIES',
  CANCER = 'CANCER',
  AMI = 'AMI',
  THYROID_DISEASES = 'THYROID_DISEASES',
  KIDNEY_DISEASES = 'KIDNEY_DISEASES',
  OTHER = 'OTHER',
}

export enum CLINICAL_HISTORY {
  SAH = 'SAH',
  DM = 'DM',
  DYSLIPIDEMIA = 'DYSLIPIDEMIA',
  CVD = 'CVD',
  OBESITY = 'OBESITY',
  CARDIOPATHIES = 'CARDIOPATHIES',
  CANCER = 'CANCER',
  AMI = 'AMI',
  THYROID_DISEASES = 'THYROID_DISEASES',
  KIDNEY_DISEASES = 'KIDNEY_DISEASES',
  GASTRITIS = 'GASTRITIS',
  GERD = 'GERD',
  HEPATIC_STEATOSIS = 'HEPATIC_STEATOSIS',
  OVERWEIGHT = 'OVERWEIGHT',
  OTHER = 'OTHER',
}

export enum SYMPTOM {
  CONSTIPATION = 'CONSTIPATION',
  HEARTBURN = 'HEARTBURN',
  DIARRHEA = 'DIARRHEA',
  FLATULENCE = 'FLATULENCE',
  NAUSEA = 'NAUSEA',
  VOMITING = 'VOMITING',
  CHOKING = 'CHOKING',
  DIFFICULTY_CHEWING = 'DIFFICULTY_CHEWING',
}
